// Mocks generated by Mockito 5.4.6 from annotations
// in sims4_name_generator/test/repositories/name_repository_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:sims4_name_generator/models/enums.dart' as _i5;
import 'package:sims4_name_generator/models/name.dart' as _i4;
import 'package:sims4_name_generator/models/trait.dart' as _i6;
import 'package:sims4_name_generator/services/data_service.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [DataService].
///
/// See the documentation for Mockito's code generation for more information.
class MockDataService extends _i1.Mock implements _i2.DataService {
  MockDataService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i4.Name>> loadNames(
    _i5.Region? region,
    _i5.Gender? gender,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#loadNames, [region, gender]),
            returnValue: _i3.Future<List<_i4.Name>>.value(<_i4.Name>[]),
          )
          as _i3.Future<List<_i4.Name>>);

  @override
  _i3.Future<List<_i6.Trait>> loadTraits() =>
      (super.noSuchMethod(
            Invocation.method(#loadTraits, []),
            returnValue: _i3.Future<List<_i6.Trait>>.value(<_i6.Trait>[]),
          )
          as _i3.Future<List<_i6.Trait>>);

  @override
  _i3.Future<void> initializeData() =>
      (super.noSuchMethod(
            Invocation.method(#initializeData, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}
